import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/ui/Header"; // НЕ должен содержать "use client"
import Footer  from "../components/ui/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
        <Footer></Footer>
       
      </body>
    </html>
  );
}
